### PR TITLE
Improve content for session `03-debugging-in-unikraft`

### PR DESCRIPTION
**Pull request by gabrielmocanu**
… 
Adding support files part. Change the name of the session. Update schedule with new naming.

Signed-off-by: Viorel-Gabriel MOCANU (94548) <viorel.mocanu@stud.acs.upb.ro>

### CODE REVIEW

**Review by razvand — CHANGES_REQUESTED** [review]
Rename the session directory to `03-debug/` or `03-debugging`. You can still call it `Session 03: Debugging in Unikraft`, but the directory name (i.e. session ID) should be shorter.

**Comment by razvand** [comment]
@gabrielmocanu , you need to rebase the commit to make it mergeable.

**Comment by gabrielmocanu** [comment]
@razvand  Done.

**Review by razvand — APPROVED** [review]
All OK.

**Pull request merged**
